export const NUM_SEQ_PROCESSES = 5
export const MAX_AVERAGE_WAITING_TIME = 10
export const ROUND_ROBIN_DEFAULT_DELTA = 4

export const DEFAULT_LOADED_TEST_DATA_AMOUNT = 5
export const DEFAULT_GENERATED_SEQUANCE_AMOUNT = 50